gui:
  authorColors:
    'Kevin de Vries': '#ffa500'
  theme:
    optionsTextColor:
      - white
  branchColorPatterns:
    '^feature/': '#00ff00'
    '^hotfix/': '#ff0000'

git:
  merging:
    args: '--no-ff'
  autoStageResolvedConflicts: false
